#line 2 "Lexer.flex.cpp"

#line 4 "Lexer.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[230] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    9,    0,    0,
        0,    0,    0,    0,    0,    0,  123,  122,    3,   78,
       94,   68,   72,  120,  106,   87,   61,   62,  114,  111,
       57,  102,   60,  116,   55,   55,   71,   56,   82,   76,
       86,   73,   67,   51,   65,   66,  118,   30,   32,   33,
       34,   35,   31,   36,   40,   37,   51,   41,   51,   51,
       51,   63,  109,   64,   69,  100,   95,  100,   93,   88,
       93,    9,    8,    6,    6,    2,    1,   77,  121,  105,

      107,  115,  112,  113,  103,  104,  101,   59,    4,    7,
      117,   55,    0,    0,    0,   70,   80,   79,   74,   75,
       83,   84,   51,   51,  119,   44,   45,   51,   51,   46,
       51,   51,   51,   18,   47,   11,   48,   49,   51,   51,
       51,   51,   51,   51,   51,   51,  110,  108,   99,   96,
       99,   99,   92,   89,   92,   92,    9,    5,    1,    1,
       58,   54,   53,   52,   81,   85,   50,   51,   51,   51,
       51,   16,   51,   51,   38,   39,   42,   43,   10,   51,
       51,   19,   27,   51,   51,   51,   51,    0,    0,    0,
        0,   26,   24,   12,   13,   20,   51,   15,   51,   51,

       28,   51,   51,   22,   25,    0,   98,   97,    0,   91,
       90,   23,   14,   29,   51,   51,    0,    0,   17,   21,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   22,   21,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   32,   32,   32,   32,   32,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   33,   33,   48,   49,   50,
       51,   52,   33,   53,   54,   55,   56,   33,   57,   58,
       59,   33,   60,   61,   62,   63,    1,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    3,
        1,    5,    3,    1,    1,    1,    1,    6,    5,    4,
        5,    5,    5,    5,    3,    3,    3,    3,    3,    3,
        7,    3,    3,    3,    3,    3,    3,    7,    3,    1,
        1,    8,    1
    } ;

static yyconst flex_int16_t yy_base[259] =
    {   0,
        0,    0,   59,   60,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   56,   57,  284,  268,    0,    0,
      257,  254,    0,    0,   64,   92,  262,  650,  650,  232,
      650,  650,  650,  227,   59,  650,  650,  650,  223,   55,
      650,   56,  214,   58,   30,  133,  201,  650,   46,   49,
       51,  650,  650,   71,  650,  650,  194,  154,  155,   96,
      156,  157,  158,  161,  159,  170,  165,  172,  164,  171,
      160,  650,  149,  650,  650,  650,  650,  222,  650,  650,
      278,    0,  650,  650,  202,  650,  162,  650,  650,  650,

      650,  650,  650,  650,  650,  650,  650,  195,  650,  650,
      650,  214,  209,  223,    0,  650,  155,  650,  650,  650,
      650,  154,  650,  163,  650,  244,  219,  235,  236,  226,
      246,  254,  255,  249,  259,  260,  269,  278,  264,  265,
      288,  297,  300,  305,  307,  308,  650,  650,  650,  650,
      121,    0,  650,  650,  120,    0,    0,  650,  650,  302,
      650,  302,  327,    0,  650,  650,  650,  321,  337,  338,
      340,  348,  349,  355,  356,  358,  360,  362,  367,  369,
      370,  371,  373,  372,  377,  380,  383,  117,    0,  116,
        0,  385,  387,  390,  400,  401,  402,  404,  408,  414,

      410,  412,  418,  420,  422,  111,  650,  650,  110,  650,
      650,  423,  425,  431,  433,  437,  108,   67,  439,  442,
       66,   65,   37,   36,   31,   28,   27,   20,  650,  492,
      500,  508,  516,  524,  532,  537,  542,  549,  557,  565,
      571,  575,  578,  580,  582,  587,  589,  594,  596,  601,
      606,  611,  616,  621,  626,  631,  636,  641
    } ;

static yyconst flex_int16_t yy_def[259] =
    {   0,
      229,    1,  230,  230,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  232,  232,  233,  233,  231,  231,
      234,  234,  231,  231,  235,  235,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  236,  229,  229,  229,  229,  229,
      229,  229,  229,  237,  229,  229,  229,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  229,  229,  229,  229,  229,  229,  238,  229,  229,
      239,  240,  229,  229,  229,  229,  241,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  242,  229,  229,  229,  229,  229,
      229,  229,  229,  237,  229,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  229,  229,  229,  229,
      229,  243,  229,  229,  229,  244,  240,  229,  229,  241,
      229,  229,  229,  242,  229,  229,  229,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  245,  246,  247,
      248,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  249,  229,  229,  250,  229,
      229,  237,  237,  237,  237,  237,  251,  252,  237,  237,
      253,  254,  255,  256,  257,  258,  229,  229,    0,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229
    } ;

static yyconst flex_int16_t yy_nxt[714] =
    {   0,
       38,   39,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       56,   56,   56,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   64,   65,   38,   66,   67,   64,   68,   69,
       70,   71,   72,   73,   64,   74,   75,   76,   77,   64,
       64,   64,   78,   79,   80,   64,   81,   64,   64,   82,
       83,   84,   85,   87,   87,   90,   90,  100,  103,  113,
      109,  105,  117,  118,  123,  110,  119,  120,  121,  122,
      114,  210,  104,  106,  107,  111,  101,  115,  207,  210,
       91,   91,  207,   88,   88,   97,   97,  210,  207,  123,

      123,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,  123,  210,  207,  210,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,  112,  112,  112,  112,  112,  112,  123,  123,  123,
      123,  123,  123,  123,  123,  159,  123,  123,  123,  207,
      112,  210,  207,  123,  123,  123,  147,  210,  207,  190,
      188,  166,  165,  123,  123,  123,  123,  123,  123,  123,
      123,  159,  123,  123,  123,  127,  133,  126,  130,  123,

      123,  123,  136,  141,  131,  128,  132,  134,  135,  148,
      146,  161,  139,  129,  143,  142,  137,  138,  144,  158,
      140,  125,  123,  145,  150,  116,  150,  162,  162,  123,
      108,  150,  112,  112,  112,  112,  112,  112,  123,  123,
      150,  163,  163,  163,  163,  163,  162,  123,  123,  123,
      102,  112,  123,  167,   99,  123,  150,  123,  123,   98,
      163,  229,  123,  123,  123,  123,   95,  123,  123,   95,
       93,  150,  123,  123,  150,  123,  150,  151,  123,  152,
      154,  123,  154,  123,  123,  168,   93,  154,  123,  123,
      169,  123,  170,  123,  123,  172,  154,  229,  123,  171,

      123,  229,  174,  123,  229,  159,  229,  123,  123,  173,
      123,  123,  154,  229,  175,  180,  176,  123,  179,  229,
      162,  162,  229,  177,  123,  178,  123,  154,  229,  123,
      154,  159,  154,  155,  123,  156,  123,  123,  182,  162,
      123,  123,  181,  123,  183,  163,  163,  163,  163,  163,
      123,  123,  123,  229,  184,  229,  229,  185,  123,  123,
      187,  123,  186,  123,  163,  123,  123,  123,  192,  123,
      123,  229,  123,  123,  123,  123,  123,  123,  123,  193,
      123,  194,  195,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  200,  123,  229,  201,  123,  196,  123,  123,

      123,  123,  123,  123,  123,  123,  123,  123,  197,  123,
      199,  123,  123,  123,  123,  123,  123,  123,  229,  123,
      198,  123,  204,  123,  205,  123,  123,  202,  123,  123,
      123,  123,  203,  123,  123,  214,  123,  123,  229,  123,
      123,  123,  123,  123,  212,  123,  229,  123,  229,  123,
      229,  123,  123,  213,  123,  229,  229,  229,  216,  229,
      123,  229,  123,  229,  215,  229,  123,  229,  123,  229,
      229,  123,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  219,  229,  229,  229,  229,  229,  229,  229,
      229,  220,   86,   86,   86,   86,   86,   86,   86,   86,

       38,   38,   38,   38,   38,   38,   38,   38,   89,   89,
       89,   89,   89,   89,   89,   89,   92,   92,   92,   92,
       92,   92,   92,   92,   94,   94,   94,   94,   94,   94,
       94,   94,   96,   96,   96,   96,   96,   96,   96,   96,
      112,  229,  112,  112,  124,  124,  124,  124,  124,  149,
      149,  149,  149,  149,  149,  149,  149,  153,  153,  153,
      153,  153,  153,  153,  153,  157,  229,  157,  157,  157,
      157,  157,  157,  160,  160,  160,  160,  160,  164,  164,
      164,  189,  189,  191,  191,  206,  206,  229,  229,  206,
      208,  208,  209,  209,  229,  229,  209,  211,  211,  217,

      217,  229,  229,  217,  218,  218,  229,  229,  218,  221,
      221,  229,  229,  221,  222,  222,  229,  229,  222,  223,
      223,  229,  229,  223,  224,  224,  229,  229,  224,  225,
      225,  229,  229,  225,  226,  226,  229,  229,  226,  227,
      227,  229,  229,  227,  228,  228,  229,  229,  228,   37,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229
    } ;

static yyconst flex_int16_t yy_chk[714] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   25,   26,   45,   50,   55,
       54,   52,   59,   59,   64,   54,   60,   60,   61,   61,
       55,  228,   50,   52,   52,   54,   45,   55,  227,  226,
       25,   26,  225,    3,    4,   35,   35,  224,  223,   70,

       64,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   36,   36,   70,  222,  221,  218,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   56,   56,   56,   56,   56,   56,   68,   69,   71,
       72,   73,   75,   81,   74,   97,  124,   79,   77,  217,
       56,  209,  206,   76,   80,   78,   83,  190,  188,  155,
      151,  122,  117,   68,   69,   71,   72,   73,   75,   81,
       74,   97,  124,   79,   77,   69,   73,   68,   71,   76,

       80,   78,   75,   77,   72,   69,   72,   73,   74,   83,
       81,  108,   76,   69,   78,   77,   75,   75,   79,   95,
       76,   67,  127,   80,   88,   57,   88,  113,  113,  130,
       53,   88,  112,  112,  112,  112,  112,  112,  128,  129,
       88,  114,  114,  114,  114,  114,  113,  126,  127,  131,
       49,  112,  134,  126,   44,  130,   88,  132,  133,   40,
      114,   37,  135,  136,  128,  129,   32,  139,  140,   31,
       28,   88,  137,  126,   88,  131,   88,   88,  134,   88,
       91,  138,   91,  132,  133,  128,   27,   91,  135,  136,
      129,  141,  131,  139,  140,  132,   91,    0,  137,  131,

      142,    0,  133,  143,    0,  160,    0,  138,  144,  132,
      145,  146,   91,    0,  137,  140,  137,  141,  139,    0,
      162,  162,    0,  138,  168,  138,  142,   91,    0,  143,
       91,  160,   91,   91,  144,   91,  145,  146,  142,  162,
      169,  170,  141,  171,  143,  163,  163,  163,  163,  163,
      168,  172,  173,    0,  143,    0,    0,  144,  174,  175,
      146,  176,  145,  177,  163,  178,  169,  170,  168,  171,
      179,    0,  180,  181,  182,  184,  183,  172,  173,  169,
      185,  170,  171,  186,  174,  175,  187,  176,  192,  177,
      193,  178,  183,  194,    0,  183,  179,  173,  180,  181,

      182,  184,  183,  195,  196,  197,  185,  198,  174,  186,
      181,  199,  187,  201,  192,  202,  193,  200,    0,  194,
      180,  203,  186,  204,  187,  205,  212,  184,  213,  195,
      196,  197,  185,  198,  214,  200,  215,  199,    0,  201,
      216,  202,  219,  200,  197,  220,    0,  203,    0,  204,
        0,  205,  212,  199,  213,    0,    0,    0,  203,    0,
      214,    0,  215,    0,  202,    0,  216,    0,  219,    0,
        0,  220,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  215,    0,    0,    0,    0,    0,    0,    0,
        0,  216,  230,  230,  230,  230,  230,  230,  230,  230,

      231,  231,  231,  231,  231,  231,  231,  231,  232,  232,
      232,  232,  232,  232,  232,  232,  233,  233,  233,  233,
      233,  233,  233,  233,  234,  234,  234,  234,  234,  234,
      234,  234,  235,  235,  235,  235,  235,  235,  235,  235,
      236,    0,  236,  236,  237,  237,  237,  237,  237,  238,
      238,  238,  238,  238,  238,  238,  238,  239,  239,  239,
      239,  239,  239,  239,  239,  240,    0,  240,  240,  240,
      240,  240,  240,  241,  241,  241,  241,  241,  242,  242,
      242,  243,  243,  244,  244,  245,  245,    0,    0,  245,
      246,  246,  247,  247,    0,    0,  247,  248,  248,  249,

      249,    0,    0,  249,  250,  250,    0,    0,  250,  251,
      251,    0,    0,  251,  252,  252,    0,    0,  252,  253,
      253,    0,    0,  253,  254,  254,    0,    0,  254,  255,
      255,    0,    0,  255,  256,  256,    0,    0,  256,  257,
      257,    0,    0,  257,  258,  258,    0,    0,  258,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[123] =
    {   0,
0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexer.l"
#line 2 "Lexer.l"
#include <iostream>
using namespace std;
#define YY_DECL extern "C" int yylex()
#include "AST.h"
#include "Register.h"
#include "Grammar.tab.h"

















#line 745 "Lexer.flex.cpp"

#define INITIAL 0
#define str 1
#define rawstr 2
#define rawstr_esc_begin 3
#define rawstr_esc_body 4
#define rawstr_esc_end 5
#define byte 6
#define bytestr 7
#define rawbytestr 8
#define rawbytestr_nohash 9
#define pound 10
#define shebang_or_attr 11
#define ltorchar 12
#define linecomment 13
#define doc_line 14
#define blockcomment 15
#define doc_block 16
#define suffix 17

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 34 "Lexer.l"


#line 954 "Lexer.flex.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 230 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 650 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "Lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 37 "Lexer.l"
{ yyless(0); BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 39 "Lexer.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "Lexer.l"
{ yy_push_state(blockcomment); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "Lexer.l"
{ yy_pop_state(); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 43 "Lexer.l"
{ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "Lexer.l"
{ BEGIN(linecomment); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 46 "Lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "Lexer.l"
{ }
	YY_BREAK
/* Keywords */
case 10:
YY_RULE_SETUP
#line 50 "Lexer.l"
{ return LET; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "Lexer.l"
{ return IF; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "Lexer.l"
{ return ELIF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "Lexer.l"
{ return ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "Lexer.l"
{ return MATCH; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "Lexer.l"
{ return LOOP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "Lexer.l"
{ return END; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "Lexer.l"
{ return RETURN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "Lexer.l"
{ return FN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "Lexer.l"
{ return MOD; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "Lexer.l"
{ return ENUM; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "Lexer.l"
{ return STRUCT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "Lexer.l"
{ return TRUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "Lexer.l"
{ return FALSE; }
	YY_BREAK
/* Types */
case 24:
YY_RULE_SETUP
#line 68 "Lexer.l"
{ return BYTE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "Lexer.l"
{ return WORD; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "Lexer.l"
{ return BOOL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "Lexer.l"
{ return REG8; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "Lexer.l"
{ return REG8; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "Lexer.l"
{ return REG16; }
	YY_BREAK
/* Registers */
case 30:
YY_RULE_SETUP
#line 76 "Lexer.l"
{ return REG_A; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "Lexer.l"
{ return REG_F; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "Lexer.l"
{ return REG_B; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "Lexer.l"
{ return REG_C; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "Lexer.l"
{ return REG_D; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "Lexer.l"
{ return REG_E; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "Lexer.l"
{ return REG_H; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "Lexer.l"
{ return REG_L; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "Lexer.l"
{ return REG_IXH; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "Lexer.l"
{ return REG_IXL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "Lexer.l"
{ return REG_I; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "Lexer.l"
{ return REG_R; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 88 "Lexer.l"
{ return REG_IYH; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "Lexer.l"
{ return REG_IYL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "Lexer.l"
{ return REG_AF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "Lexer.l"
{ return REG_BC; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "Lexer.l"
{ return REG_DE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "Lexer.l"
{ return REG_HL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "Lexer.l"
{ return REG_IX; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "Lexer.l"
{ return REG_IY; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 96 "Lexer.l"
{ return REG_AFS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "Lexer.l"
{ return NAME; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "Lexer.l"
{ BEGIN(suffix); return TINTEGER; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "Lexer.l"
{ BEGIN(suffix); return TINTEGER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "Lexer.l"
{ BEGIN(suffix); return TINTEGER; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "Lexer.l"
{ BEGIN(suffix); return TINTEGER; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "Lexer.l"
{ return ';'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "Lexer.l"
{ return ','; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "Lexer.l"
{ return DOTDOTDOT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "Lexer.l"
{ return DOTDOT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "Lexer.l"
{ return '.'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "Lexer.l"
{ return '('; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "Lexer.l"
{ return ')'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "Lexer.l"
{ return '{'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "Lexer.l"
{ return '}'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 114 "Lexer.l"
{ return '['; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 115 "Lexer.l"
{ return ']'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 116 "Lexer.l"
{ return '@'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 117 "Lexer.l"
{ return '#'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "Lexer.l"
{ return '~'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "Lexer.l"
{ return MOD_SEP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "Lexer.l"
{ return ':'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "Lexer.l"
{ return '$'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "Lexer.l"
{ return '?'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "Lexer.l"
{ return EQEQ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "Lexer.l"
{ return FAT_ARROW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "Lexer.l"
{ return '='; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "Lexer.l"
{ return NE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "Lexer.l"
{ return '!'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "Lexer.l"
{ return LE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "Lexer.l"
{ return SHL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "Lexer.l"
{ return SHLEQ; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "Lexer.l"
{ return '<'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "Lexer.l"
{ return GE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 134 "Lexer.l"
{ return SHR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "Lexer.l"
{ return SHREQ; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "Lexer.l"
{ return '>'; }
	YY_BREAK
/* CHARS */
case 87:
YY_RULE_SETUP
#line 139 "Lexer.l"
{ BEGIN(ltorchar); yymore(); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "Lexer.l"
{ BEGIN(suffix); return TCHARS; }
	YY_BREAK
case YY_STATE_EOF(ltorchar):
#line 141 "Lexer.l"
{ return -1; }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 142 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "Lexer.l"
{ return -1; }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 146 "Lexer.l"
{ yymore(); }
	YY_BREAK
/* STRING */
case 94:
YY_RULE_SETUP
#line 149 "Lexer.l"
{ BEGIN(str); yymore(); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 150 "Lexer.l"
{ BEGIN(suffix); return TSTRING; }
	YY_BREAK
case YY_STATE_EOF(str):
#line 151 "Lexer.l"
{ return -1; }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 152 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 153 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 154 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 155 "Lexer.l"
{ return -1; }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 156 "Lexer.l"
{ yymore(); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 158 "Lexer.l"
{ return RARROW; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 159 "Lexer.l"
{ return '-'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 160 "Lexer.l"
{ return MINUSMINUS; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 161 "Lexer.l"
{ return MINUSEQ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 162 "Lexer.l"
{ return ANDAND; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 163 "Lexer.l"
{ return '&'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 164 "Lexer.l"
{ return ANDEQ; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 165 "Lexer.l"
{ return OROR; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 166 "Lexer.l"
{ return '|'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 167 "Lexer.l"
{ return OREQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 168 "Lexer.l"
{ return '+'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 169 "Lexer.l"
{ return PLUSPLUS; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 170 "Lexer.l"
{ return PLUSEQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 171 "Lexer.l"
{ return '*'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 172 "Lexer.l"
{ return STAREQ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 173 "Lexer.l"
{ return '/'; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 174 "Lexer.l"
{ return SLASHEQ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 175 "Lexer.l"
{ return '^'; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 176 "Lexer.l"
{ return CARETEQ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 177 "Lexer.l"
{ return '%'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 178 "Lexer.l"
{ return PERCENTEQ; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(rawstr):
case YY_STATE_EOF(rawstr_esc_begin):
case YY_STATE_EOF(rawstr_esc_body):
case YY_STATE_EOF(rawstr_esc_end):
case YY_STATE_EOF(byte):
case YY_STATE_EOF(bytestr):
case YY_STATE_EOF(rawbytestr):
case YY_STATE_EOF(rawbytestr_nohash):
case YY_STATE_EOF(pound):
case YY_STATE_EOF(shebang_or_attr):
case YY_STATE_EOF(linecomment):
case YY_STATE_EOF(doc_line):
case YY_STATE_EOF(blockcomment):
case YY_STATE_EOF(doc_block):
case YY_STATE_EOF(suffix):
#line 179 "Lexer.l"
{ return 0; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 181 "Lexer.l"
ECHO;
	YY_BREAK
#line 1703 "Lexer.flex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 230 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 230 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 229);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "Lexer.l"



